### ISSUE TITLE
How do you categorize bug

### ISSUE THREAD

**Issue by liuchintao** [masud-technope/BLIZZARD-Replication-Package-ESEC-FSE2018#1]
Hi, I am interesting about your research and your BLIZZARD, it's cool. But I have a little question about your tool.
According to your paper FSE 2018, the process of categorize bug report is a semi-automated approach. But the tool you provided on GitHub do not involve manual parts.

**Comment by masud-technope** [comment]
We used regular expressions to identify different structured elements, and classify the bug reports.
You might be looking for Section 3.1 here.
http://homepage.usask.ca/~masud.rahman/papers/masud-ESECFSE2018.pdf

**Comment by liuchintao** [comment]
> We used regular expressions to identify different structured elements, and classify the bug reports.
> You might be looking for Section 3.1 here.
> http://homepage.usask.ca/~masud.rahman/papers/masud-ESECFSE2018.pdf

OH! Thanks a lot 👍 ~ On the other hand, I am very interested in your tool, and I want to use BLIZZARD to find out the **ranked buggy files list** of other project's bug report, such as ZooKeeper, Hibernate and such so on.

But I found that BLIZZARD used lucene-core to index project source code, and can you tell me which **Field** need to be added for **Documents** and what kind of **Lucene-Analyzer** have you choose?

wish you have a nice day. :-)

**Comment by masud-technope** [comment]
Thanks for your interest in our work. Hope this helps!
https://gist.github.com/masud-technope/00392277fca55fab236b1baf44aa94c2

**Comment by liuchintao** [comment]
Thanks for your code! Do I still need to check the NL bug reports collection again after categorizing bug reports? After all, the last paragraph of section 3.1 mentioned that there is process of manual checking of misclassification?

**Comment by masud-technope** [comment]
Basically, the manual analysis is needed for the BR_ST category. If the stack traces are too much ill-structured, then regular expressions might fail to detect them. So, in this work, we did some preprocessing to make each  trace on a single line, and removed some unnecessary elements.
https://github.com/masud-technope/BLIZZARD-Replication-Package-ESEC-FSE2018/blob/master/BR-ST-StackTraces/ecf/164154.txt
While we did that manually, you could possibly write a program for that. 
Anyway, once the traces are fine, our prototype should be able to classify the bug reports into their desired classes, and generate appropriate reformulations for them.

Good luck!

**Comment by liuchintao** [comment]
OK! Thanks for your answer:-) your reply really help me a lot.
It's a really  delightful journey of study.

**Comment by masud-technope** [comment]
Good to know it worked :) Good luck with journey !
